### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/pyqt-feedback-flow#10]
@luckyLukac, do you have any ideas regarding the design of test cases?

**Comment by luckyLukac** [comment]
I would have to think about it, so far I haven't really encountered good opportunities for test cases. Do you have any idea regarding this matter?

**Comment by firefly-cpp** [comment]
No ideas.

**Comment by firefly-cpp** [comment]
@zStupan, can you maybe help in improving tests?

**Comment by firefly-cpp** [comment]
@KukovecRok
